Repository AY2021S1-CS2113-T13-2/tp, pull requests merged in 2020-10, with the labels that each got.

#39 Fixes #23
  src/main/java/command/action/McAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/seedu/duke/Duke.java
  src/test/java/seedu/duke/McActionTest.java
Labels: priority.High

#40 Merge Added JUnit Test
  src/main/java/command/action/FocusAction.java
  src/main/java/seedu/duke/Duke.java
  src/test/java/command/action/FocusActionTest.java
  src/test/java/seedu/duke/McActionTest.java
Labels: priority.High

#53 Updated Item. Updated Date. Fixed Next and Prev. Completed UI Dynamic Update. Fixed Find, Focus, List, Delete, Done, Undone.
  data/duke.txt
  src/main/java/command/Command.java
  src/main/java/command/action/Action.java
  src/main/java/command/action/AddAction.java
  src/main/java/command/action/CalculateCapAction.java
  src/main/java/command/action/ClearAction.java
  src/main/java/command/action/DeadlineAction.java
  src/main/java/command/action/DeleteAction.java
  src/main/java/command/action/DetailAction.java
  src/main/java/command/action/DoneAction.java
  src/main/java/command/action/EventAction.java
  src/main/java/command/action/FancyAction.java
  src/main/java/command/action/FindAction.java
  src/main/java/command/action/FocusAction.java
  src/main/java/command/action/HelpAction.java
  src/main/java/command/action/ListAction.java
  src/main/java/command/action/McAction.java
  src/main/java/command/action/NextAction.java
  src/main/java/command/action/PlainAction.java
  src/main/java/command/action/PrevAction.java
  src/main/java/command/action/TodoAction.java
  src/main/java/command/action/UndoneAction.java
  src/main/java/command/action/UnknownAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Data.java
  src/main/java/data/Item.java
  src/main/java/data/ParentModules.java
  src/main/java/data/ParentTask.java
  src/main/java/data/SingleModule.java
  src/main/java/data/TaskList.java
  src/main/java/io/FileSaver.java
  src/main/java/io/ReadFile.java
  src/main/java/io/Storage.java
  src/main/java/jobs/Task.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/visualize/Cli.java
  src/main/java/visualize/FancyCli.java
  src/main/java/visualize/UI.java
  src/test/java/command/action/TasksActionTest.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Epic

#95 v1.0 merge j checks. created JUnit test for Todo Action
  data/duke.txt
  src/test/java/command/action/TodoActionTest.java
Labels: priority.High, severity.Low, type.Task

#98 V1.0 do j unit test tasks
  data/duke.txt
  src/test/java/command/action/FocusActionTest.java
Labels: priority.High, severity.Low, type.Task

#101 v1.0 allow Exceptions, fixed Bugs, Implemented features
  data/duke.txt
  src/main/java/command/Command.java
  src/main/java/command/ParamNode.java
  src/main/java/command/action/Action.java
  src/main/java/command/action/AddAction.java
  src/main/java/command/action/CalculateCapAction.java
  src/main/java/command/action/ClearAction.java
  src/main/java/command/action/DeadlineAction.java
  src/main/java/command/action/DeleteAction.java
  src/main/java/command/action/DetailAction.java
  src/main/java/command/action/DoneAction.java
  src/main/java/command/action/EventAction.java
  src/main/java/command/action/FancyAction.java
  src/main/java/command/action/FindAction.java
  src/main/java/command/action/FocusAction.java
  src/main/java/command/action/HelpAction.java
  src/main/java/command/action/ListAction.java
  src/main/java/command/action/McAction.java
  src/main/java/command/action/NextAction.java
  src/main/java/command/action/PlainAction.java
  src/main/java/command/action/PrevAction.java
  src/main/java/command/action/SelectAction.java
  src/main/java/command/action/TakeAction.java
  src/main/java/command/action/TodoAction.java
  src/main/java/command/action/UndoneAction.java
  src/main/java/command/action/UnknownAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Data.java
  src/main/java/data/Item.java
  src/main/java/data/SingleModule.java
  src/main/java/data/jobs/Deadline.java
  src/main/java/data/jobs/Event.java
  src/main/java/data/jobs/Task.java
  src/main/java/data/jobs/ToDo.java
  src/main/java/exceptions/CommandException.java
  src/main/java/exceptions/ItemNotSpecifiedException.java
  src/main/java/exceptions/ModuleNotFoundException.java
  src/main/java/exceptions/TaskNotSpecifiedException.java
  src/main/java/io/FileSaver.java
  src/main/java/io/Storage.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/visualize/FancyCli.java
  src/test/java/command/action/FocusActionTest.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Story, type.Task

#111 V1.0 Included auto wrap for long text, included blank character handling, greatly simplified detail action, added more flexibility
  data/duke.txt
  src/main/java/command/Command.java
  src/main/java/command/action/Action.java
  src/main/java/command/action/ClearAction.java
  src/main/java/command/action/DetailAction.java
  src/main/java/command/action/SelectAction.java
  src/main/java/command/action/TakeAction.java
  src/main/java/command/action/UnselectAction.java
  src/main/java/command/action/UntakeAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Item.java
  src/main/java/data/SingleModule.java
  src/test/java/command/action/DetailActionTest.java
Labels: priority.High, priority.Medium, type.Bug, type.Enhancement

#117 V1.0 reminderaction
  data/duke.txt
  src/main/java/command/Command.java
  src/main/java/command/ParamNode.java
  src/main/java/command/action/Action.java
  src/main/java/command/action/AddAction.java
  src/main/java/command/action/CalculateCapAction.java
  src/main/java/command/action/ClearAction.java
  src/main/java/command/action/DeadlineAction.java
  src/main/java/command/action/DeleteAction.java
  src/main/java/command/action/DetailAction.java
  src/main/java/command/action/DoneAction.java
  src/main/java/command/action/EventAction.java
  src/main/java/command/action/FancyAction.java
  src/main/java/command/action/FindAction.java
  src/main/java/command/action/FocusAction.java
  src/main/java/command/action/HelpAction.java
  src/main/java/command/action/ListAction.java
  src/main/java/command/action/McAction.java
  src/main/java/command/action/NextAction.java
  src/main/java/command/action/PlainAction.java
  src/main/java/command/action/PrevAction.java
  src/main/java/command/action/ReminderAction.java
  src/main/java/command/action/SelectAction.java
  src/main/java/command/action/TakeAction.java
  src/main/java/command/action/TodoAction.java
  src/main/java/command/action/UndoneAction.java
  src/main/java/command/action/UnknownAction.java
  src/main/java/command/action/UnselectAction.java
  src/main/java/command/action/UntakeAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Data.java
  src/main/java/data/Item.java
  src/main/java/data/SingleModule.java
  src/main/java/data/jobs/Deadline.java
  src/main/java/data/jobs/Event.java
  src/main/java/data/jobs/Task.java
  src/main/java/data/jobs/ToDo.java
  src/main/java/exceptions/CommandException.java
  src/main/java/exceptions/ItemNotSpecifiedException.java
  src/main/java/exceptions/ModuleNotFoundException.java
  src/main/java/exceptions/TaskNotSpecifiedException.java
  src/main/java/io/FileSaver.java
  src/main/java/io/Storage.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/visualize/FancyCli.java
  src/test/java/command/action/DetailActionTest.java
  src/test/java/command/action/FocusActionTest.java
  src/test/java/command/action/TodoActionTest.java
Labels: priority.High, type.Enhancement, type.Task

#122 Add Reminder. Able to see Reminders from Welcome Message. Merge V1.0_Reminder
  src/main/java/command/action/ReminderAction.java
  src/main/java/command/action/SelectAction.java
  src/main/java/command/action/TakeAction.java
  src/main/java/constants/Constants.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/visualize/UI.java
  src/test/java/command/action/ReminderActionTest.java
Labels: priority.Medium, type.Enhancement, type.Epic, type.Story, type.Task

#123 Add Reminder. Able to show Reminder on welcome message. Merge V1.0_Reminder_BackUp
  data/duke.txt
  src/main/java/command/action/ReminderAction.java
  src/main/java/command/action/SelectAction.java
  src/main/java/command/action/TakeAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/visualize/UI.java
  src/test/java/command/action/TaskActionTest.java
Labels: priority.Medium, type.Enhancement, type.Epic, type.Story, type.Task

#129 V1.0 optimize code fix bugs
  data/duke.txt
  src/main/java/command/action/FindAction.java
  src/main/java/command/action/TakeAction.java
  src/main/java/constants/Constants.java
  src/main/java/data/Data.java
Labels: priority.Medium, severity.Medium, type.Bug

#137 Add logging and assertion in focus and reminder. Merge johanesrafael/V1.0_reminder
  data/duke.txt
  src/main/java/command/action/DoneAction.java
  src/main/java/command/action/FocusAction.java
  src/main/java/command/action/ReminderAction.java
Labels: severity.Low, type.Bug, type.Task

#141 V1.0 optimize code fix bugs
  build.gradle
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
  src/main/java/command/action/AddAction.java
  src/main/java/command/action/ClearAction.java
  src/main/java/command/action/McAction.java
  src/main/java/command/action/TakeAction.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Data.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Enhancement, type.Task

#148 Updated User Guide, Help Text, fixed minor bug
  data/duke.txt
  docs/README.md
  docs/UserGuide.md
  src/main/java/constants/HelpText.java
  src/main/java/data/SingleModule.java
  src/main/java/io/ModuleParser.java
  src/main/java/io/Storage.java
  src/main/java/seedu/duke/Duke.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Enhancement

#149 JUnit, Assertions, Logging
  src/main/java/visualize/UI.java
  src/test/java/command/action/TaskActionTest.java
Labels: type.Task

#151 Assertions and Logging
  src/main/java/visualize/UI.java
Labels: type.Task

#154 V1.0 pre release
  docs/README.md
  docs/UserGuide.md
  src/main/java/command/action/DeleteAction.java
  src/main/java/constants/Constants.java
  src/main/java/data/Data.java
  src/main/java/visualize/FancyCli.java
  src/test/java/command/action/TaskActionTest.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Enhancement

#152 Update userguide
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement, type.Task

#160 Fix website
  docs/README.md
Labels: priority.Medium, severity.VeryLow, type.Task

#161 Fix Picture
  UI.png
  docs/README.md
  src/main/java/visualize/FancyCli.java
Labels: priority.Medium, severity.VeryLow, type.Task

#162 V1.0 reminderaction
  data/duke.txt
  src/main/java/command/action/PostponeAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/seedu/duke/Duke.java
Labels: priority.Medium, type.Enhancement

#165 Add Postpone Action. Add Postpone options. Merge branch tp/V2.0_postpone
  src/main/java/command/action/PostponeAction.java
  src/main/java/command/action/RemindAction.java
  src/main/java/command/action/SnoozeAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Item.java
  src/main/java/visualize/UI.java
  src/test/java/command/action/PostponeActionTest.java
Labels: priority.High, type.Task

#176 V2.0 features
  docs/DeveloperGuide.md
  docs/Package visualize.png
  docs/lexical.uml
  docs/visualize.uml
Labels: priority.Medium, severity.VeryLow, type.Task

#177 V2.0 developer guide
  docs/DeveloperGuide.md
  docs/ReminderAction_Sequence_Diagram.png
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
Labels: priority.High, type.Enhancement

#178 Fix bug on timer and userguide hyperlink
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
Labels: priority.Medium, type.Bug, type.Enhancement

#179 Update DeveloperGuide.md for V2.0
  docs/DeveloperGuide.md
  docs/PostponeAction_Sequence_Diagram.png
  src/main/java/data/Item.java
Labels: priority.High, type.Task

#192 V2.0 user guide
  docs/DeveloperGuide.md
  docs/Images/DOMSUM_Main_Flow.png
  docs/UserGuide.md
Labels: priority.High, type.Task

#196 Implement new Snooze action and new Remind action. Merge branch V2.0_snooze
  data/course.txt
  src/main/java/command/Command.java
  src/main/java/command/action/RemindAction.java
  src/main/java/command/action/ReminderAction.java
  src/main/java/command/action/SnoozeAction.java
  src/main/java/constants/Constants.java
  src/main/java/seedu/duke/Duke.java
Labels: priority.High, type.Enhancement, type.Task

#198 V2.0 user guide
  docs/DeveloperGuide.md
  docs/Images/ReminderAction_Sequence_Diagram.png
  docs/UserGuide.md
  src/main/java/command/action/ViewtrashAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/seedu/duke/Duke.java
Labels: priority.Medium, type.Task

#204 Fix sequence diagram and extra \
  docs/DeveloperGuide.md
  docs/Images/DOMSUM_Main_Flow.png
Labels: priority.Low, type.Enhancement

#210 Fixed reminder bugs. Updated Developer Guide.
  docs/DeveloperGuide.md
  src/main/java/command/action/SnoozeAction.java
  src/main/java/constants/Constants.java
Labels: priority.High, severity.High, type.Bug, type.Task

#212 V2.0 features
  data/course.txt
  data/duke.txt
  src/main/java/command/action/EditAction.java
  src/main/java/command/action/GradeAction.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Item.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#214 Add reminder on/off functionality and update userguide
  docs/UserGuide.md
  src/main/java/command/action/ReminderAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/seedu/duke/Duke.java
Labels: priority.High, type.Enhancement

#217 Update User Guide
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
Labels: type.Task

#218 V2.0 pre release
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Medium, type.Enhancement, type.Task
