Repository AY2021S1-CS2113-T13-2/tp, pull requests merged in 2020-11, with the labels that each got.

#250 Update developer guide
  docs/DeveloperGuide.md
  docs/Images/DOMNUS_Main_Flow.png
  src/test/java/data/CheckerTest.java
Labels: priority.High, type.Bug

#254 Minor update in User Guide. Reformat some documentation.
  docs/UserGuide.md
  docs/team/johanesrafael.md
  src/main/java/command/Command.java
  src/main/java/command/action/PostponeAction.java
  src/main/java/command/action/RemindAction.java
  src/main/java/command/action/ReminderAction.java
  src/main/java/command/action/SnoozeAction.java
  src/main/java/command/action/StatsAction.java
  src/main/java/command/action/UntakeAction.java
  src/main/java/constants/Constants.java
  src/main/java/seedu/duke/Domnus.java
  src/test/java/command/action/FocusActionTest.java
  src/test/java/command/action/PostponeActionTest.java
  src/test/java/command/action/ReminderActionTest.java
Labels: priority.Medium, type.Bug, type.Enhancement, type.Task

#265 Restructure userguide flow
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#266 Update userguide with edit functionality
  data/duke.txt
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#267 Reorganize userguide
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#270 V2.1 bug fixes
  META-INF/MANIFEST.MF
  build.gradle
  data/course.txt
  data/duke.txt
  docs/UserGuide.md
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/command/Command.java
  src/main/java/command/Help.java
  src/main/java/command/action/Action.java
  src/main/java/command/action/AddAction.java
  src/main/java/command/action/CalculateCapAction.java
  src/main/java/command/action/CapAction.java
  src/main/java/command/action/ClearAction.java
  src/main/java/command/action/CompleteAction.java
  src/main/java/command/action/DeadlineAction.java
  src/main/java/command/action/DeleteAction.java
  src/main/java/command/action/DoneAction.java
  src/main/java/command/action/EventAction.java
  src/main/java/command/action/GoalAction.java
  src/main/java/command/action/GradeAction.java
  src/main/java/command/action/NextAction.java
  src/main/java/command/action/PrevAction.java
  src/main/java/command/action/ReminderAction.java
  src/main/java/command/action/SelectAction.java
  src/main/java/command/action/TakeAction.java
  src/main/java/command/action/TodoAction.java
  src/main/java/command/action/UndoneAction.java
  src/main/java/command/action/UnselectAction.java
  src/main/java/command/action/UntakeAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Checker.java
  src/main/java/data/Data.java
  src/main/java/data/Item.java
  src/main/java/data/SingleModule.java
  src/main/java/exceptions/MissingDescriptionException.java
  src/main/java/exceptions/ModuleException.java
  src/main/java/exceptions/TooManyArgumentsException.java
  src/main/java/exceptions/TypeMismatchException.java
  src/main/java/seedu/duke/Domsun.java
  src/main/java/visualize/Cli.java
  src/main/java/visualize/FancyCli.java
  src/main/java/visualize/UI.java
  src/main/resources/META-INF/MANIFEST.MF
  src/test/java/command/action/CapActionTest.java
  src/test/java/command/action/FocusActionTest.java
  src/test/java/command/action/GoalActionTest.java
Labels: priority.High, priority.Medium, severity.High, severity.Medium, type.Bug, type.Task

#273 V2.1 user guide
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#277 Restructure user guide flow
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#292 Fix minor formatting issue for userguide
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#295 Remove unpeer-reviewed function
  src/main/java/command/Command.java
  src/main/java/command/action/RemindAction.java
  src/main/java/constants/Constants.java
  src/main/java/seedu/duke/Domsun.java
Labels: severity.Low, type.Story, type.Task

#296 V2.1 userguide
  docs/UserGuide.md
  src/main/java/constants/HelpText.java
Labels: priority.High, type.Enhancement

#297 Fix Postponing invalid Date for event or deadline Bug
  data/duke.txt
  src/main/java/command/action/PostponeAction.java
  src/main/java/constants/Constants.java
  src/main/java/data/Data.java
  src/main/java/data/Item.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Task

#272 V2.1 bug fixes2
  data/course.txt
  data/duke.txt
  docs/team/tomlbz.md
  src/main/java/command/action/ClearAction.java
  src/main/java/command/action/EditAction.java
  src/main/java/command/action/NextAction.java
  src/main/java/command/action/PrevAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/lexical/Parser.java
  src/main/java/visualize/Cli.java
  src/main/java/visualize/FancyCli.java
  src/main/java/visualize/UI.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Enhancement

#299 Reformat SnoozeAction and Update HelpText
  docs/UserGuide.md
  docs/team/johanesrafael.md
  src/main/java/command/action/SnoozeAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/seedu/duke/Domsun.java
Labels: severity.Low, type.Bug, type.Task

#300 V2.1 enhancements
  data/course.txt
  data/duke.txt
  docs/Images/ansicodes.png
  docs/Images/dwdvalue.png
  docs/Images/dword.png
  docs/Images/dwordMod.png
  docs/Images/hkeyConsole.png
  docs/Images/newUI.png
  docs/Images/regedit.png
  docs/Images/textui.png
  docs/Images/winTerm.png
  docs/UserGuide.md
  src/main/java/command/action/EditAction.java
  src/main/java/command/action/LoadLinkedTasksAction.java
  src/main/java/constants/Constants.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Item.java
  src/main/java/data/SingleModule.java
  src/main/java/data/jobs/Deadline.java
  src/main/java/data/jobs/Event.java
  src/main/java/data/jobs/Task.java
  src/main/java/io/FileSaver.java
  src/main/java/io/Storage.java
  src/test/java/command/action/ModuleActionTest.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Task

#302 Update UG, HelpText, SnoozeActionTest, ReminderActionTest, PostponeActionTest, and start filling PPP
  docs/UserGuide.md
  docs/team/johanesrafael.md
  src/main/java/command/action/FocusAction.java
  src/main/java/command/action/PostponeAction.java
  src/main/java/command/action/ReminderAction.java
  src/main/java/command/action/SnoozeAction.java
  src/main/java/constants/HelpText.java
  src/main/java/data/Item.java
  src/main/java/seedu/duke/Domsun.java
  src/test/java/command/action/PostponeActionTest.java
  src/test/java/command/action/ReminderActionTest.java
  src/test/java/command/action/SnoozeActionTest.java
Labels: priority.Medium, type.Enhancement, type.Story, type.Task

#304 V2.1 user guide
  docs/AboutUs.md
  docs/Images/Focus.png
  docs/Images/PostponeAction_Sequence_Diagram.png
  docs/UserGuide.md
  docs/team/chuhann.md
Labels: priority.High, type.Enhancement

#307 Remove ``` from user guide
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#308 Remove more ``` for formatting issue
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#311 Remove reminder feature from developer guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Enhancement

#313 Update user guide with load functionality
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#315 Update invidiual PPP
  docs/team/chuhann.md
Labels: priority.High

#316 Add PPP
  docs/team/chuhann.md
Labels: priority.High

#317 V2.1 pre release
  docs/UserGuide.md
  docs/team/tomlbz.md
Labels: type.Enhancement

#319 Update userguide
  docs/Images/DOMNUS_Main_Flow.png
  docs/UserGuide.md
Labels: priority.High, type.Enhancement
